### ISSUE TITLE
Consider preventing word wrap in header nav

### ISSUE THREAD

**Issue by kp77** [openeuropa/bootstrap-component-library#669]
The UCPKN project has a relatively long main navigation and on smaller screen sizes a multi-word nav item breaks into 2 lines.

<img width="930" alt="Image" src="https://github.com/user-attachments/assets/266722d6-b249-4c66-beca-1eaac33f3389" />

We are fixing it with the following override:

```scss
.bcl-header__navbar {
  .navbar-nav {
    .nav-link {
      white-space: nowrap;
    }
  }
}
```

Note: some of the menu items are dropdown toggles, that [receive the nowrap rule from bootstrap](https://github.com/twbs/bootstrap/blob/v5.3.5/scss/_dropdown.scss#L12), this makes the wrapping behavior in the menu inconsistent.

Please consider adding the above rule either to the default header style, or if it's not possible to the [UCPKN header overrides](https://github.com/openeuropa/bootstrap-component-library/blob/development/src/themes/ucpkn/src/scss/_header.scss).
